### ISSUE TITLE
cannot use template due to `postcss-nesting`

### ISSUE THREAD

**Issue by scarf005** [lumeland/theme-simple-blog#10]
```ts
 deno task lume
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A -
Loading config file file:///home/scarf/repo/blog/_config.ts

Warning Implicitly using latest version (v0.7.0) for https://deno.land/x/lume_theme_simple_blog/mod.ts

TypeError: Could not find npm package 'postcss-nesting' matching 11.2.1. Try retrieving the latest npm package information by running with --reload
    at async createSite (https://deno.land/x/lume@v1.15.3/cli/run.ts:50:17)
    at async build (https://deno.land/x/lume@v1.15.3/cli/build.ts:28:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.15.3/cli.ts:158:3)
```
i think there's problem resolving package postcss-nesting in the template.

**Comment by oscarotero** [comment]
This is a bug from Deno related to how it's cached the npm modules data. More info here: https://github.com/denoland/deno/issues/16901

You can run `deno cache --reload _config.ts` to reload the cache of your _config.ts file. It should fix it.

**Comment by scarf005** [comment]
thank you! it works now.
